### ISSUE TITLE
Dosyaya yazma hatası

### ISSUE THREAD

**Issue by zafer06** [ozanselte/dgpio#1]
```
import std.stdio;
import dgpio;

void main()
{
     writefln("Raspberry PI Led Yakmak");

     GPIO pin18 = new GPIO(18);
     pin18.setOutput();
     pin18.setLow();
     pin18.setHigh();
     pin18.deactivate();
}
```

Yukarıdaki kodu çalıştırdığımda aşağıdaki hatayı alıyorum. Kullandığım sistem  Raspbery PI2 (ARMv7 Processor rev 5 (v7l)) üzerinde  Linux raspberrypi 4.1.13-v7+.

> pi@raspberrypi ~/projects/led $ ./a.out 
> Raspberry PI Led Yakmak
> ## std.exception.ErrnoException@../../../../src/libphobos/src/std/stdio.d(368): Cannot open file `/sys/class/gpio/18/direction' in mode`w' (No such file or directory)
> 
> 0x2a197 _d_throw
>   ../../../../src/libphobos/libdruntime/gcc/deh.d:144
> 0x8e02b shared(core.stdc.stdio._IO_FILE)\* std.exception.__T12errnoEnforceTPOS4core4stdc5stdio8_IO_FILEVAyaa41_2e2e2f2e2e2f2e2e2f2e2e2f7372632f6c696270686f626f732f7372632f7374642f737464696f2e64Vk368Z.errnoEnforce(shared(core.stdc.stdio._IO_FILE)_, lazy immutable(char)[])
>   /usr/src/packages/BUILD/gcc-4.8-4.8.2/src/libphobos/src/std/exception.d:503
> 0x89237 ref std.stdio.File std.stdio.File.__ctor(immutable(char)[], const(char[]))
>   ../../../../src/libphobos/src/std/stdio.d:368
> 0x10b23 void dgpio.GPIO.writeLine(immutable(char)[], immutable(char)[])
>   ???:0
> 0x10f3f void dgpio.GPIO.setOutput()
>   ???:0
> 0xe21f _Dmain
>   ???:0
> 0x1a503 void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).runAll().void __lambda1()
>   ../../../../src/libphobos/libdruntime/rt/dmain2.d:412
> 0x1aad7 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate())
>   ../../../../src/libphobos/libdruntime/rt/dmain2.d:387
> 0x1acff void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll()
>   ../../../../src/libphobos/libdruntime/rt/dmain2.d:412
> 0x1aad7 void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate())
>   ../../../../src/libphobos/libdruntime/rt/dmain2.d:387
> 0x1ac1b _d_run_main
>   ../../../../src/libphobos/libdruntime/rt/dmain2.d:420
> 0xe1ab main
>   ???:0
> 0x76dbc81b ???
> ##   ???:0
> 
> Segmentation fault
> pi@raspberrypi ~/projects/led $

**Comment by ozanselte** [comment]
Sorun son güncellemedeki klasör adının yanlış girilmesinden meydana gelmiş. Az önce düzelttim. Teşekkürler.

**Comment by zafer06** [comment]
Düzenlenmiş son sürümü indirdim ancak aynı sorun devam ediyor.

pi@raspberrypi ~/projects/led $ ./led 
Raspberry PI Led Yakmak

## std.exception.ErrnoException@../../../../src/libphobos/src/std/stdio.d(368): Cannot open file `/sys/class/gpio/gpio18/direction' in mode`w' (Permission denied)

0x28b87 _d_throw
    ../../../../src/libphobos/libdruntime/gcc/deh.d:144
0x8cf4b shared(core.stdc.stdio._IO_FILE)\* std.exception.__T12errnoEnforceTPOS4core4stdc5stdio8_IO_FILEVAyaa41_2e2e2f2e2e2f2e2e2f2e2e2f7372632f6c696270686f626f732f7372632f7374642f737464696f2e64Vk368Z.errnoEnforce(shared(core.stdc.stdio._IO_FILE)_, lazy immutable(char)[])
    /usr/src/packages/BUILD/gcc-4.8-4.8.2/src/libphobos/src/std/exception.d:503
0x88157 ref std.stdio.File std.stdio.File.__ctor(immutable(char)[], const(char[]))
    ../../../../src/libphobos/src/std/stdio.d:368
0xfd67 void dgpio.GPIO.writeLine(immutable(char)[], immutable(char)[])
    ???:0
0x10183 void dgpio.GPIO.setOutput()
    ???:0
0xe21f _Dmain
    ???:0
0x18ef3 void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).runAll().void __lambda1()
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:412
0x194c7 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate())
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:387
0x196ef void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll()
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:412
0x194c7 void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate())
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:387
0x1960b _d_run_main
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:420
0xe1ab main
    ???:0
0x76cfb81b ???

##     ???:0

Segmentation fault
pi@raspberrypi ~/projects/led $

**Comment by ozanselte** [comment]
Hocam sudo kullanarak dener misiniz? Yine olmazsa "ls /sys/class/gpio" çıktısını yazar mısınız?

**Comment by zafer06** [comment]
Projeyi _sudo_ ile çalıştırınca aşağıdaki hatayı veriyor. Sanırım kodların bir kısmını işletiyor çünkü ledlerin yandığını görüyorum ama sönmüyorlar.

```
pi@raspberrypi ~/projects/led $ sudo ./led
Raspberry PI Led Yakmak
std.exception.ErrnoException@../../../../src/libphobos/src/std/stdio.d(528): Could not close file `/sys/class/gpio/export' (Device or resource busy)
----------------
0x28b87 _d_throw
    ../../../../src/libphobos/libdruntime/gcc/deh.d:144
0x8d233 bool std.exception.errnoEnforce!(bool, "../../../../src/libphobos/src/std/stdio.d", 528u).errnoEnforce(bool, lazy immutable(char)[])
    /usr/src/packages/BUILD/gcc-4.8-4.8.2/src/libphobos/src/std/exception.d:503
0x89483 close
    ../../../../src/libphobos/src/std/stdio.d:528
0x89483 detach
    ../../../../src/libphobos/src/std/stdio.d:470
0x89483 void std.stdio.File.__dtor()
    ../../../../src/libphobos/src/std/stdio.d:376
0xfd8b void dgpio.GPIO.writeLine(immutable(char)[], immutable(char)[])
    ???:0
0x10033 void dgpio.GPIO.deactivate()
    ???:0
0xe267 _Dmain
    ???:0
0x18ef3 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll().void __lambda1()
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:412
0x194c7 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate())
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:387
0x196ef void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:412
0x194c7 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate())
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:387
0x1960b _d_run_main
    ../../../../src/libphobos/libdruntime/rt/dmain2.d:420
0xe1ab main
    ???:0
0x76d0181b ???
    ???:0
----------------
pi@raspberrypi ~/projects/led $ 
```

**"ls /sys/class/gpio"** çıktısı şu şekilde;

```
pi@raspberrypi ~ $ ls -l /sys/class/gpio
total 0
-rwxrwx--- 1 root gpio 4096 Jan  1  1970 export
lrwxrwxrwx 1 root gpio    0 Jan  1  1970 gpiochip0 -> ../../devices/platform/soc/3f200000.gpio/gpio/gpiochip0
-rwxrwx--- 1 root gpio 4096 Jan  1  1970 unexport
pi@raspberrypi ~ $ 
```

**Comment by ozanselte** [comment]
Hocam kodu sıfırdan yazarken unuttulan bir yerden kaynaklanmış. Kusura bakmayın.

**Comment by zafer06** [comment]
Kusura bakılacak bir durum yok, Hata yapmak, yeni bir şeyler geliştirmenin doğasında var. Belki onlarca, yüzlece hata olacak, önemli olan pes etmeden sonucu ulaşabilmek.

Çabaların için teşekkürler, kütüphane gayet güzel çalışıyor. Python'da yaptığım kodlamayı senin kütüphaneni kullanarak D dilinde tekrar yazdım ve sorunsuz çalıştırdım. Teşekkürler.
